version: "3.2"
services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - '27017:27017'

  auth:
    # command: node authentication/src/server.js
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/authentication
    environment:
      JWT_SECRET: 'blabla'
  movies:
    build:
      context: ./movies
      dockerfile: Dockerfile
    # context: .



    # dockerfile: ./movies/Dockerfile
    ports:
      - published: ${APP_PORT:-3001}
        target: 3001
    volumes:
      - ./movies:/movies
    environment:
      JWT_SECRET: 'blabla'
      # DB_URI: mongodb://mongo:27017/movies
