version: "3.2"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    command: mongod --quiet
    ports:
      - 27017:27017
    networks:
      - my-network
  auth:
    container_name: auth
    # command: node authentication/src/server.js
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - my-network
    volumes:
      - /authentication
    environment:
      # JWT_SECRET: 'blabla'
      JWT_SECRET: ${JWT_SECRET}
    
  movies:
    container_name: movies
    build:
      context: ./movies
      dockerfile: Dockerfile
    # context: .



    # dockerfile: ./movies/Dockerfile
    ports:
      - 3001:3001
    networks:
      - my-network
    volumes:
      - /movies
    depends_on:
      - auth
    environment:
      JWT_SECRET: ${JWT_SECRET}
      # JWT_SECRET: 'blabla'
      DB_URI: 'mongodb://mongo:27017/moviesDb'
      OMDB_KEY: ${OMDB_KEY} 
      COOKIE_KEY: ${COOKIE_KEY} 
networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
