name: Docker Image CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    env: 
     OMDB_KEY: ${{secrets.OMDB_KEY}}
     COOKIE_KEY: ${{secrets.COOKIE_KEY}}
     JWT_SECRET: ${{secrets.JWT_SECRET}}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs --details	movies
      
     
